---
# Configuration directives for Travis CI

language: python  # Needed to run ansible

python:
  - "2.7"

install:
  - pip install ansible

script:
  - ansible-playbook -i inventory test.yml
  #- ansible-playbook -i travis-ci-inventory travis-ci-test.yml
